sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
notifications:
  email:
    - dev@joeir.net
stages:
  - build
  - publish
before_script:
  - docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}";
after_script:
  - docker logout
jobs:
  include:
    - stage: build
      env:
        - TAG_NAME=gke-deployer
      script:
        - ./scripts/build ${TAG_NAME}
        - ./${TAG_NAME}/publish zephinzer/${TAG_NAME}
    - stage: build
      env:
        - TAG_NAME=docker-runner
      script:
        - ./scripts/build ${TAG_NAME}
        - ./${TAG_NAME}/publish zephinzer/${TAG_NAME}
    - stage: build
      env:
        - TAG_NAME=ci-runner-node-argon
      script:
        - ./scripts/build ${TAG_NAME}
        - docker tag zephinzer/${TAG_NAME}:next zephinzer/ci-runner-node:argon
        - ./${TAG_NAME}/publish zephinzer/ci-runner-node
    - stage: build
      env:
        - TAG_NAME=ci-runner-node-boron
      script:
        - ./scripts/build ${TAG_NAME}
        - docker tag zephinzer/${TAG_NAME}:next zephinzer/ci-runner-node:boron
        - ./${TAG_NAME}/publish zephinzer/ci-runner-node
    - stage: build
      env:
        - TAG_NAME=ci-runner-node-carbon
      script:
        - ./scripts/build ${TAG_NAME}
        - docker tag zephinzer/${TAG_NAME}:next zephinzer/ci-runner-node:carbon
        - ./${TAG_NAME}/publish zephinzer/ci-runner-node
    - stage: publish
      script:
        - ./scripts/publish