#!/bin/bash
CURR_DIR=$(dirname $0);
TAG_NAME=$1;
BUILD_ARGS=$2;
if [[ "${TAG_NAME}" = "" ]]; then
  printf "\n\e[31m\e[1m[!] Specify the image (directory name) to build as the first argument.\e[0m\n";
  exit 1;
fi;

REPOSITORY_URL=zephinzer/${TAG_NAME};
NEXT_TAG="${REPOSITORY_URL}:next";
if [[ "${BUILD_ARGS}" = "" ]]; then
  ADDITIONAL_BUILD_ARGS="$(echo "${BUILD_ARGS}" | sed -e $'s|,|\\\n|g' | xargs -I @ echo '--build-arg @')";
else
  ADDITIONAL_BUILD_ARGS="";
fi;

docker build \
  ${ADDITIONAL_BUILD_ARGS} \
  --file ./${TAG_NAME}/Dockerfile \
  --tag "${NEXT_TAG}" \
  ${CURR_DIR}/../${TAG_NAME};
