#!/bin/bash
REPOSITORY_URL=$1;

TAG="${REPOSITORY_URL}:next";
TAG_LATEST="${REPOSITORY_URL}:latest";

VERSIONS=$(docker run ${TAG});
VERSION_GCLOUD=$(printf "${VERSIONS}" | grep gcloud | cut -f 2 -d ':');
VERSION_GIT=$(printf "${VERSIONS}" | grep git | cut -f 2 -d ':');
VERSION_DOCKER=$(printf "${VERSIONS}" | grep docker | cut -f 2 -d ':');
VERSION_KUBECTL=$(printf "${VERSIONS}" | grep kubectl | cut -f 2 -d ':');
EXISTENCE_TAG="gcloud-${VERSION_GCLOUD}_docker-${VERSION_DOCKER}_kubectl-${VERSION_KUBECTL}_git-${VERSION_GIT}";
EXISTENCE_REPO_URL="${REPOSITORY_URL}:${EXISTENCE_TAG}";
GCLOUD_VERSION_REPO_URL="${REPOSITORY_URL}:${VERSION_GCLOUD}";

printf "Checking existence of [${EXISTENCE_REPO_URL}]...";
$(docker pull ${EXISTENCE_REPO_URL}) && EXISTS=$?;
if [[ "$EXISTS" = "0" ]]; then
  printf "[${EXISTENCE_REPO_URL}] found. Skipping push.\n";
  echo exists;
else
  printf "[${EXISTENCE_REPO_URL}] not found. Pushing new image...\n";
  printf "Pushing [${EXISTENCE_REPO_URL}]... ";
  docker tag ${TAG} ${EXISTENCE_REPO_URL};
  docker push ${EXISTENCE_REPO_URL};
  printf "Pushing [${GCLOUD_VERSION_REPO_URL}]... ";
  docker tag ${TAG} ${GCLOUD_VERSION_REPO_URL};
  docker push ${GCLOUD_VERSION_REPO_URL};
  printf "Pushing [${TAG}]... ";
  docker tag ${TAG} ${TAG_LATEST};
  docker push ${TAG_LATEST};
fi;