#!/bin/sh
printf "gcloud:$(gcloud version --format='json' | jq '."Google Cloud SDK"' | cut -d '"' -f 2)\n";
printf "git:$(git --version | cut -d ' ' -f 3)\n";
printf "docker:$(docker -v | cut -f 5 -d ' ')\n";
printf "kubectl:$(kubectl version --client --output='json' | jq '.clientVersion|.gitVersion' | cut -d '"' -f 2)\n";