#!/bin/bash
REPOSITORY_URL=$1;

TAG="${REPOSITORY_URL}:next";
TAG_LATEST="${REPOSITORY_URL}:latest";

VERSIONS=$(docker run ${TAG});
VERSION_AWS=$(printf "${VERSIONS}" | grep aws | cut -f 2 -d ':');
VERSION_GIT=$(printf "${VERSIONS}" | grep git | cut -f 2 -d ':');
VERSION_PYTHON=$(printf "${VERSIONS}" | grep python | cut -f 2 -d ':');
VERSION_DOCKER=$(printf "${VERSIONS}" | grep docker | cut -f 2 -d ':');
EXISTENCE_TAG="aws-${VERSION_AWS}_git-${VERSION_GIT}_python-${VERSION_PYTHON}_docker-${VERSION_DOCKER}";
EXISTENCE_REPO_URL="${REPOSITORY_URL}:${EXISTENCE_TAG}";
REPO_URL="${REPOSITORY_URL}:${VERSION_AWS}";

printf "Checking existence of [${EXISTENCE_REPO_URL}]...";
$(docker pull ${EXISTENCE_REPO_URL}) && EXISTS=$?;
if [[ "$EXISTS" = "0" ]]; then
  printf "[${EXISTENCE_REPO_URL}] found. Skipping push.\n";
  echo exists;
else
  printf "[${EXISTENCE_REPO_URL}] not found. Pushing new image...\n";
  printf "Pushing [${EXISTENCE_REPO_URL}]... ";
  docker tag ${TAG} ${EXISTENCE_REPO_URL};
  docker push ${EXISTENCE_REPO_URL};
  printf "Pushing [${REPO_URL}]... ";
  docker tag ${TAG} ${REPO_URL};
  docker push ${REPO_URL};
  printf "Pushing [${TAG}]... ";
  docker tag ${TAG} ${TAG_LATEST};
  docker push ${TAG_LATEST};
fi;