#!/bin/sh
VERSION=$(aws --v &> ./.test);
VERSION_AWSCLI=$(cat ./.test | cut -f 1 -d ' ' | cut -f 2 -d '/')
VERSION_PYTHON=$(cat ./.test | cut -f 2 -d ' ' | cut -f 2 -d '/')
VERSION_GIT="$(git --version | cut -d ' ' -f 3)";
VERSION_DOCKER="$(docker -v | cut -f 5 -d ' ' | cut -f 2 -d 'v')";
printf "aws:${VERSION_AWSCLI}\n";
printf "python:${VERSION_PYTHON}\n";
printf "git:${VERSION_GIT}\n";
printf "docker:${VERSION_DOCKER}\n";